name: precompile-linux-gnu

on:
  workflow_dispatch:
    inputs:
      openssl_verison:
        description: 'OpenSSL Version'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  linux-gnu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64, riscv64, ppc64le, s390x]

    name: ${{ matrix.arch }}-linux-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull docker image
        run: |
          if [ "${{ matrix.arch }}" = "riscv64" ]; then
            sudo docker pull --platform=linux/${{ matrix.arch }} riscv64/ubuntu:22.04
          else
            sudo docker pull quay.io/pypa/manylinux_2_28_${{ matrix.arch }}:latest
          fi

      - name: Install binfmt
        if: matrix.arch != 'x86_64'
        run: |
          sudo apt update
          sudo apt install -y binfmt-support qemu-user-static

      - name: Precompile
        run: |
          export OPENSSL_VERSION=${{ github.event.inputs.openssl_verison }}
          export OPENSSL_VERSION="${OPENSSL_VERSION##*v}" 
          cp .github/script-to-build-gnu.sh ./
          cp .github/do-build.sh ./

          bash ./script-to-build-gnu.sh "${OPENSSL_VERSION}" "${{ matrix.arch }}"

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.openssl_verison }}
          name: ${{ github.event.inputs.openssl_verison }}
          files: |
            openssl-*.tar.gz
