name: precompile-x86_64-apple-darwin-catalina

on:
  workflow_dispatch:
    inputs:
      openssl_verison:
        description: 'OpenSSL Version'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  macos:
    runs-on: self-hosted-x86_64-apple-darwin-catalina
    name: x86_64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download OpenSSL Source Code
        run: |
          export OPENSSL_VERSION=${{ github.event.inputs.openssl_verison }}
          export OPENSSL_VERSION=${GITHUB_REF##*/v}
          echo "$OPENSSL_VERSION"
          if [[ "${OPENSSL_VERSION}" == 3.* ]]; then
            curl -fSL "https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz" -o "openssl-${OPENSSL_VERSION}.tar.gz"
          elif [[ "${OPENSSL_VERSION}" == 1.1.1* ]]; then
            curl -fSL "https://openssl.org/source/old/1.1.1/openssl-${OPENSSL_VERSION}.tar.gz" -o "openssl-${OPENSSL_VERSION}.tar.gz"
          fi
          
          tar -xzf "openssl-${OPENSSL_VERSION}.tar.gz"

      - name: Compile OpenSSL
        run: |
          export OPENSSL_VERSION=${{ github.event.inputs.openssl_verison }}
          export OPENSSL_VERSION=${GITHUB_REF##*/v}
          export ROOTDIR="$(pwd)"
          export PERFIX_DIR="/tmp/openssl-x86_64-apple-darwin"
          mkdir -p "${PERFIX_DIR}"
          cd "openssl-${OPENSSL_VERSION}"
          mkdir build
          if [[ "${OPENSSL_VERSION}" == 3.* ]]; then
            ./Configure --prefix="${PERFIX_DIR}" --openssldir="${PERFIX_DIR}" darwin64-x86_64 no-tests
          elif [[ "${OPENSSL_VERSION}" == 1.1.1* ]]; then
            ./Configure --prefix="${PERFIX_DIR}" --openssldir="${PERFIX_DIR}" darwin64-x86_64-cc
          fi

          make -j"$(sysctl -n hw.ncpu)"
          make -j"$(sysctl -n hw.ncpu)" install_sw
          make -j"$(sysctl -n hw.ncpu)" install_ssldirs
          mkdir -p "${ROOTDIR}/build"
          cd "${PERFIX_DIR}"
          tar -czf "${ROOTDIR}/build/openssl-x86_64-apple-darwin-catalina.tar.gz" .

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*.tar.gz

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.event.inputs.openssl_verison, 'v')
        with:
          tag_name: ${{ github.event.inputs.openssl_verison }}
          name: ${{ github.event.inputs.openssl_verison }}
          files: |
            build/*.tar.gz

  deploy-macos:
    runs-on: ubuntu-latest
    needs: macos
    steps:
      - name: deploy
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'cocoa-xu/openssl-build'
        env:
          DEPLOY_MACOS_CATALINA_HOOK_URL: ${{ secrets.DEPLOY_MACOS_CATALINA_HOOK_URL }}
        run: |
          curl -sS --no-progress-meter "${DEPLOY_MACOS_CATALINA_HOOK_URL}${{ github.ref_name }}"
